// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import remarkWikiLinks from './src/utils/wikilink-remark.mjs';
import { sharedHead } from './src/head.mjs';

// Note: public/graph.json (the wiki link graph) is generated by
// `node scripts/build-graph.mjs`, chained ahead of `astro build` in
// package.json (see the "build" script).

// https://astro.build/config
export default defineConfig({
	site: 'https://xh.asxz.one',
	markdown: {
		remarkPlugins: [
			// Wiki-link [[…]] / ![[…]] syntax, ported from the old xuehai-wiki-doc.
			remarkWikiLinks,
		],
	},
	integrations: [
		starlight({
			title: 'Xuehai Docs',
			// Starlight 0.41 无 route 选项;docs 挂载在根路径的 [...slug] 上。
			// 内容 entry id 统一加 'docs/' 前缀(见 src/content.config.ts),使文档只服务于 /docs/*。
			disable404Route: true, // 全站自定义 404 (src/pages/404.astro)
			lastUpdated: true, // 页脚显示 git 最后修改时间
			customCss: ['./src/styles/global.css'],
			components: {
				// 在 Starlight 页面外壳里把免责 banner 作为组件插到顶栏与内容之间
				// (替代运行时注入的浮层)。见 src/components/starlight/PageFrame.astro。
				PageFrame: './src/components/starlight/PageFrame.astro',
				// 统一 /docs 顶栏与全站 Nav(品牌+链接),右侧保留 Starlight 搜索与主题切换
				Header: './src/components/starlight/Header.astro',
				// 在每个 /docs 页面底部注入"反向链接"(wiki 链接图驱动)
				Footer: './src/components/starlight/Footer.astro',
				// 维基式文章标题栏:标题下方注入分类标签 + 最后更新 + 字数/章节数 + 随机文章
				PageTitle: './src/components/starlight/PageTitle.astro',
			},
			head: [
				// 全站共享 head(umami + theme-init):单一事实来源 src/head.mjs,
				// 与自定义页面 BaseLayout 保持一致,避免重复。
				...sharedHead,
				// Starlight 页面没有自定义 BaseLayout,通过此处 head 注入与自定义页面
				// 一致的脚本与样式(banner/页脚注入 + 主题同步)。由 designer A 负责维护。
				{
					tag: 'script',
					attrs: { src: '/starlight-globals.js', defer: false },
				},
				// Starlight 与全站主题打通(同一 html[data-theme] + 双向同步 key)
				{
					tag: 'script',
					attrs: { src: '/starlight-theme-sync.js', defer: false },
				},
			],
		}),
	],
});